title: Anton Fagerberg
email: anton@antonfagerberg.com
description: >- # this means to ignore newlines until "baseurl:"
  The personal website of Anton Fagerberg, it's about programming, reading books and other things I find interesting.
baseurl: ""
url: "https://www.antonfagerberg.com"
permalink: /:categories/:title/


plugins:
  - jekyll-feed

collections:
  books:
    output: true
