# Site settings
title: Anton Fagerberg
email: anton@antonfagerberg.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.antonfagerberg.com" # the base hostname & protocol for your site
twitter_username: antonfagerberg

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/

gems: []

collections:
- book_posts
- record_posts